News/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from News import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('accaunts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.get_article_by_category, name='get_article_by_category'),
    path('tag/<int:tag_id>/', views.get_article_by_tag, name='get_article_by_tag'),
    path('article/<int:pk>', views.detail_article, name= 'article_detail'),
    path('add_article/', views.add_article, name= 'add_article'),
    path('add_category/', views.add_category, name= 'add_category'),
    path('add_tags/', views.add_tags, name= 'add_tags'),
    path('article_edit/<int:pk>/', views.EditArticleVies.as_view(), name= 'edit_article'),
    path('add_comment/<int:pk>/', views.add_comment, name= 'add_comment'),
    path('delete_comment/<int:comment_id>/ <article_id>', views.delete_comment, name= 'delete_comment'),
    path('create_like/<int:pk>/', views.create_like, name= 'create_like'),
]

main/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from accaunts.models import CustomUser

class Author(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    @property
    def count_posts(self):
        return self.author_articles.all().count()

    def __str__(self):
        return self.user.username




class Category(models.Model):
    category_name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.category_name


class Tags(models.Model):
    tag_name = models.CharField(max_length=255)

    def __str__(self):
        return self.tag_name


class Article(models.Model):
    title = models.CharField(max_length=255)
    summary = models.TextField()
    content = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.PROTECT, related_name='author_articles')
    published_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    image_url = models.ImageField(upload_to='media', blank=True)
    tags = models.ManyToManyField(Tags)
    views = models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.title

    def publish(self):
        self.save()

    class Meta:
        ordering = ['-published_date']

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk":self.pk})

class Comments(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


    class Like(models.Model):
        user = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='user_likes')
        article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes')

        def __str__(self):
            return self.article.title

main/forms.py
from django import forms
from .models import Article, Category, Tags, Comments


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'summary', 'content', 'author', 'category', 'image_url', 'tags']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name', 'description']

class TagsForm(forms.ModelForm):
    class Meta:
        model = Tags
        fields = ['tag_name']

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, DeleteView


from .models import Article, Category, Comments
from .forms import ArticleForm, CategoryForm, TagsForm, CommentsForm



def index(request):
    articles = Article.objects.all()
    categories = Category.objects.all()
    context = {
        'article_list': articles,
        'categories': categories
    }
    return render(request, 'main/index.html', context)


def get_article_by_category(request, category_id):
    articles = Article.objects.filter(category__id=category_id)
    categories = Category.objects.all()
    context = {
        'article_list': articles,
        'categories': categories
    }
    return render(request, 'main/index.html', context)


def get_article_by_tag(request, tag_id):
    articles = Article.objects.filter(tags__id=tag_id)
    categories = Category.objects.all()
    context = {
        'article_list': articles,
        'categories': categories
    }
    return render(request, 'main/index.html', context)


def detail_article(request, pk):
    article = get_object_or_404(Article, id=pk)
    article.views += 1
    article.save()

    form = CommentsForm()
    user_has_liked = article.likes.filter(user=request.user.author).exists()
    context = {
        'article': article,
        'form': form,
        'user_has_liked': user_has_liked,
    }
    return render(request, 'main/detail_article.html', context)

def add_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = ArticleForm()
    context = {
        'form':form
    }
    return render(request, 'main/add_article.html', context)

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = CategoryForm()
    context = {
        'form':form
    }
    return render(request, 'main/add_category.html', context)

def add_tags(request):
    if request.method == 'POST':
        form = TagsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = TagsForm()
    context = {
        'form':form
    }
    return render(request, 'main/add_tags.html', context)



class EditArticleVies(UpdateView):
    model = Article
    template_name = 'main/edit_article.html'
    form_class = ArticleForm

def add_comment(request, pk):
    article = get_object_or_404(Article, id=pk)
    if request.method == 'POST':
        form = CommentsForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.user = request.user.author
            comment.save()
            return redirect('article_detail', pk=article.id)

def delete_comment(request, comment_id, article_id):
    Comments.objects.filter(id=comment_id).delete()
    return redirect('article_detail', article_id)

def create_like(request, pk):
    article = get_object_or_404(Article, id=pk)
    if request.user.is_authenticated:
        if request.user.author and article.likes.filter(user=request.user.author).exists():
            article.likes.filter(user=request.user.author).delete()
        else:
            article.likes.create(user=request.user.author)
        return redirect('article_detail', pk=article.id)
    else:
        return redirect('login')

templates/main/add_article.html
{% extends 'base.html' %}

{% block title %} Detail article {% endblock title %}


{% block content %}

<div class="container mt-4">
    <h4>Add Article</h4>
    <form action="{% url 'add_article' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</div>

{% endblock content %}

templates/main/add_category.html
{% extends 'base.html' %}

{% block title %} Detail article {% endblock title %}


{% block content %}

<div class="container mt-4">
    <h4>Add Category</h4>
    <form action="{% url 'add_category' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</div>

{% endblock content %}

templates/main/add_tags.html
{% extends 'base.html' %}

{% block title %} Detail article {% endblock title %}


{% block content %}

<div class="container mt-4">
    <h4>Add Tags</h4>
    <form action="{% url 'add_tags' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</div>

{% endblock content %}

templates/main/detail_article.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Detail article {% endblock title %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <a href="{% url 'edit_article' article.id %}">
                    <input class="btn btn-success" type="submit" value="Редактировать">
                </a>
                <h1>{{ article.title }}</h1>
                <p class="text-muted">by {{ article.author }} | {{ article.published_date }}</p>
                {% if article.image_url %}
                    <img src="{{ article.image_url.url }}" alt="{{ article.title }}" class="card-img-top">
                {% endif %}
                <p>{{ article.summary }}</p>
                <hr>
                <div>{{ article.content | safe }}</div>
                <hr>
                <p class="tag-container">
                    <strong>Tags:</strong>
                    {% for tag in article.tags.all %}
                    <a href="{% url 'get_article_by_tag' tag.id %}">
                        <span class="badge bg-primary-gradient">#{{ tag.tag_name }}</span>
                    </a>
                    {% endfor %}
                </p>
            </div>
            <p>Просмотры: {{ article.views }}</p>
              <a id="like-button" href="{% url 'create_like' article.id %}" class="like-button">
                    <img src="{% if user_has_liked %}
                                    {% static 'heart-regular.jpg' %}
                               {% else %}
                                    {% static 'heart-solid.jpg' %}
                               {% endif %}"
                         alt="Like" width="20px">
                   <span id="like-count" class="like-count">{{ article.likes.count }}</span> Нравится
                        </a>
            <div class="comments mt-3">
                <h3>Комментарии</h3>
                {% for comment in article.comments_set.all %}
                    <div class="card mb-4 shadow-sm">
                        <div class="card-header py-3">
                            <h5 class="m-0">{{ comment.user}}</h5>
                        </div>
                    <div class="card-body">
                        <p class="card-text">{{ comment.text }}</p>
                    </div>
                         <div class="card-body">
                        <p class="card-text">{{ comment.created_date }}</p>

                    </div>
                        {% if request.user.author == comment.user %}
                        <a href="{% url 'delete_comment' comment.id article.id %}" class="btn btn-primary">Удалить</a>
                        {% endif %}
                </div>
            {% endfor %}
        </div>

<form action="{% url 'add_comment' article.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Отправить">
</form>
        </div>
{% endblock content %}

templates/main/edit_article.html
{% extends 'base.html' %}

{% block title %} Detail article {% endblock title %}


{% block content %}

<div class="container mt-4">
    <h4>Edit Article</h4>
    <form action="{% url 'edit_article' article.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-success" type="submit" value="Изменить">
        <a href="{% url 'article_detail' article.id %}">
        <input class="btn btn-danger" value="Отменить">
        </a>
    </form>
</div>

{% endblock content %}

templates/main/index.html
{% extends "base.html" %}


{% block title %}Articles{% endblock title %}

{% block content %}
<div class="row mb-4">
    <div class="col-12">
        <h2 class="mb-3">Categories</h2>
        <div class="d-flex flex-wrap">
            {% for i in categories %}
            <a href="{% url 'get_article_by_category' i.id %}" class="btn btn-primary-gradient me-2 mb-2">{{ i.category_name }}</a>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row">
    {% for article in article_list %}
    <div class="col-md-4 mb-4">
        <div class="card h-100 shadow-lg">
            {% if article.image_url %}
            <img src="{{ article.image_url.url }}" class="card-img-top article-image" alt="{{ article.title }}">
            {% else %}
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/1200px-Flag_of_Kyrgyzstan.svg.png" class="card-img-top article-image" alt="{{ article.title }}">
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">
                    <a href="{% url 'article_detail' article.id %}" class="text-dark">{{ article.title }}</a>
                </h5>
                <p class="card-text">{{ article.content|truncatewords:20 }}</p>
                <p class="card-subtitle text-muted mb-2">by {{ article.author }} | {{ article.date }}</p>
                <p>Просмотры: {{ article.views }}</p>

                    <span id="like-count" class="like-count">{{ article.article_likes.count }}</span> Нравится
                </a>
                <p class="tag-container">
                    <strong>Tags:</strong>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'get_article_by_tag' tag.id %}">
                            <span class="badge bg-primary-gradient">{{ tag.tag_name }}</span>
                        </a>
                    {% endfor %}
                </p>

            </div>


        </div>
    </div>
    {% endfor %}
</div>


{% endblock content %}